sudo : required
services:
    - docker

before_install: 
    - docker build -t avinashkumar15/docker-react-test -f Dockerfile.dev .

script: 
    - docker run -e CI=true avinashkumar15/docker-react-test npm run test
    
